// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accountmanager.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnlockAccountRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Passphrase           []byte   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockAccountRequest) Reset()         { *m = UnlockAccountRequest{} }
func (m *UnlockAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockAccountRequest) ProtoMessage()    {}
func (*UnlockAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba6db06a1aaf83a, []int{0}
}

func (m *UnlockAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockAccountRequest.Unmarshal(m, b)
}
func (m *UnlockAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockAccountRequest.Marshal(b, m, deterministic)
}
func (m *UnlockAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockAccountRequest.Merge(m, src)
}
func (m *UnlockAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockAccountRequest.Size(m)
}
func (m *UnlockAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockAccountRequest proto.InternalMessageInfo

func (m *UnlockAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UnlockAccountRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type LockAccountRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockAccountRequest) Reset()         { *m = LockAccountRequest{} }
func (m *LockAccountRequest) String() string { return proto.CompactTextString(m) }
func (*LockAccountRequest) ProtoMessage()    {}
func (*LockAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba6db06a1aaf83a, []int{1}
}

func (m *LockAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockAccountRequest.Unmarshal(m, b)
}
func (m *LockAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockAccountRequest.Marshal(b, m, deterministic)
}
func (m *LockAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockAccountRequest.Merge(m, src)
}
func (m *LockAccountRequest) XXX_Size() int {
	return xxx_messageInfo_LockAccountRequest.Size(m)
}
func (m *LockAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockAccountRequest proto.InternalMessageInfo

func (m *LockAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type UnlockAccountResponse struct {
	State                ResponseState `protobuf:"varint,1,opt,name=state,proto3,enum=v1.ResponseState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnlockAccountResponse) Reset()         { *m = UnlockAccountResponse{} }
func (m *UnlockAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockAccountResponse) ProtoMessage()    {}
func (*UnlockAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba6db06a1aaf83a, []int{2}
}

func (m *UnlockAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockAccountResponse.Unmarshal(m, b)
}
func (m *UnlockAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockAccountResponse.Marshal(b, m, deterministic)
}
func (m *UnlockAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockAccountResponse.Merge(m, src)
}
func (m *UnlockAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockAccountResponse.Size(m)
}
func (m *UnlockAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockAccountResponse proto.InternalMessageInfo

func (m *UnlockAccountResponse) GetState() ResponseState {
	if m != nil {
		return m.State
	}
	return ResponseState_UNKNOWN
}

type LockAccountResponse struct {
	State                ResponseState `protobuf:"varint,1,opt,name=state,proto3,enum=v1.ResponseState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LockAccountResponse) Reset()         { *m = LockAccountResponse{} }
func (m *LockAccountResponse) String() string { return proto.CompactTextString(m) }
func (*LockAccountResponse) ProtoMessage()    {}
func (*LockAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba6db06a1aaf83a, []int{3}
}

func (m *LockAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockAccountResponse.Unmarshal(m, b)
}
func (m *LockAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockAccountResponse.Marshal(b, m, deterministic)
}
func (m *LockAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockAccountResponse.Merge(m, src)
}
func (m *LockAccountResponse) XXX_Size() int {
	return xxx_messageInfo_LockAccountResponse.Size(m)
}
func (m *LockAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockAccountResponse proto.InternalMessageInfo

func (m *LockAccountResponse) GetState() ResponseState {
	if m != nil {
		return m.State
	}
	return ResponseState_UNKNOWN
}

type GenerateRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Types that are valid to be assigned to Params:
	//	*GenerateRequest_Distributed
	Params               isGenerateRequest_Params `protobuf_oneof:"Params"`
	Passphrase           []byte                   `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GenerateRequest) Reset()         { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()    {}
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba6db06a1aaf83a, []int{4}
}

func (m *GenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRequest.Unmarshal(m, b)
}
func (m *GenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRequest.Marshal(b, m, deterministic)
}
func (m *GenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRequest.Merge(m, src)
}
func (m *GenerateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRequest.Size(m)
}
func (m *GenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRequest proto.InternalMessageInfo

func (m *GenerateRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type isGenerateRequest_Params interface {
	isGenerateRequest_Params()
}

type GenerateRequest_Distributed struct {
	Distributed *GenerateDistributedKeyParams `protobuf:"bytes,2,opt,name=distributed,proto3,oneof"`
}

func (*GenerateRequest_Distributed) isGenerateRequest_Params() {}

func (m *GenerateRequest) GetParams() isGenerateRequest_Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenerateRequest) GetDistributed() *GenerateDistributedKeyParams {
	if x, ok := m.GetParams().(*GenerateRequest_Distributed); ok {
		return x.Distributed
	}
	return nil
}

func (m *GenerateRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GenerateRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GenerateRequest_Distributed)(nil),
	}
}

type GenerateDistributedKeyParams struct {
	Participants         uint32   `protobuf:"varint,1,opt,name=participants,proto3" json:"participants,omitempty"`
	SigningThreshold     uint32   `protobuf:"varint,2,opt,name=signing_threshold,json=signingThreshold,proto3" json:"signing_threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateDistributedKeyParams) Reset()         { *m = GenerateDistributedKeyParams{} }
func (m *GenerateDistributedKeyParams) String() string { return proto.CompactTextString(m) }
func (*GenerateDistributedKeyParams) ProtoMessage()    {}
func (*GenerateDistributedKeyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba6db06a1aaf83a, []int{5}
}

func (m *GenerateDistributedKeyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateDistributedKeyParams.Unmarshal(m, b)
}
func (m *GenerateDistributedKeyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateDistributedKeyParams.Marshal(b, m, deterministic)
}
func (m *GenerateDistributedKeyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateDistributedKeyParams.Merge(m, src)
}
func (m *GenerateDistributedKeyParams) XXX_Size() int {
	return xxx_messageInfo_GenerateDistributedKeyParams.Size(m)
}
func (m *GenerateDistributedKeyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateDistributedKeyParams.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateDistributedKeyParams proto.InternalMessageInfo

func (m *GenerateDistributedKeyParams) GetParticipants() uint32 {
	if m != nil {
		return m.Participants
	}
	return 0
}

func (m *GenerateDistributedKeyParams) GetSigningThreshold() uint32 {
	if m != nil {
		return m.SigningThreshold
	}
	return 0
}

type GenerateResponse struct {
	State                ResponseState `protobuf:"varint,1,opt,name=state,proto3,enum=v1.ResponseState" json:"state,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PublicKey            []byte        `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Participants         []*Endpoint   `protobuf:"bytes,4,rep,name=participants,proto3" json:"participants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GenerateResponse) Reset()         { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()    {}
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba6db06a1aaf83a, []int{6}
}

func (m *GenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateResponse.Unmarshal(m, b)
}
func (m *GenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateResponse.Marshal(b, m, deterministic)
}
func (m *GenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateResponse.Merge(m, src)
}
func (m *GenerateResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateResponse.Size(m)
}
func (m *GenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateResponse proto.InternalMessageInfo

func (m *GenerateResponse) GetState() ResponseState {
	if m != nil {
		return m.State
	}
	return ResponseState_UNKNOWN
}

func (m *GenerateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GenerateResponse) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *GenerateResponse) GetParticipants() []*Endpoint {
	if m != nil {
		return m.Participants
	}
	return nil
}

func init() {
	proto.RegisterType((*UnlockAccountRequest)(nil), "v1.UnlockAccountRequest")
	proto.RegisterType((*LockAccountRequest)(nil), "v1.LockAccountRequest")
	proto.RegisterType((*UnlockAccountResponse)(nil), "v1.UnlockAccountResponse")
	proto.RegisterType((*LockAccountResponse)(nil), "v1.LockAccountResponse")
	proto.RegisterType((*GenerateRequest)(nil), "v1.GenerateRequest")
	proto.RegisterType((*GenerateDistributedKeyParams)(nil), "v1.GenerateDistributedKeyParams")
	proto.RegisterType((*GenerateResponse)(nil), "v1.GenerateResponse")
}

func init() {
	proto.RegisterFile("accountmanager.proto", fileDescriptor_aba6db06a1aaf83a)
}

var fileDescriptor_aba6db06a1aaf83a = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x26, 0xdd, 0x28, 0xdb, 0x59, 0x5b, 0x36, 0xb7, 0xb0, 0xb6, 0xfb, 0xa1, 0x84, 0x0b, 0x10,
	0x68, 0x09, 0x2d, 0xf7, 0x08, 0xaa, 0x4d, 0x20, 0x31, 0xa4, 0x2a, 0x03, 0x09, 0x4d, 0x48, 0xc3,
	0x4d, 0xad, 0xc4, 0x5a, 0x6b, 0x87, 0xd8, 0x29, 0xda, 0x2d, 0x3c, 0x02, 0x97, 0xdc, 0x23, 0xc4,
	0xa3, 0x70, 0xcb, 0x2b, 0xf0, 0x20, 0xd8, 0x71, 0xc2, 0x9a, 0xae, 0x02, 0x4d, 0x5c, 0x9e, 0xef,
	0xf8, 0xfb, 0xce, 0x39, 0x9f, 0x8f, 0x0d, 0x0d, 0xec, 0xfb, 0x3c, 0x61, 0x72, 0x82, 0x19, 0x0e,
	0x48, 0xec, 0x44, 0x31, 0x97, 0x1c, 0x95, 0xa6, 0xdd, 0xf6, 0x76, 0xc0, 0x79, 0x30, 0x26, 0x2e,
	0x8e, 0xa8, 0x8b, 0x19, 0xe3, 0x12, 0x4b, 0xca, 0x99, 0x30, 0x27, 0xda, 0xf5, 0x98, 0x88, 0x48,
	0x85, 0x44, 0x28, 0x9c, 0x64, 0x60, 0x8d, 0xb0, 0x51, 0xc4, 0x29, 0x93, 0x26, 0xb6, 0x07, 0xd0,
	0x78, 0xcd, 0xc6, 0xdc, 0x3f, 0x7d, 0x6a, 0x8a, 0x78, 0xe4, 0x7d, 0xa2, 0x08, 0xa8, 0x09, 0xd7,
	0xb2, 0xb2, 0x4d, 0xab, 0x63, 0xdd, 0x5b, 0xf5, 0xf2, 0x10, 0xed, 0x02, 0x44, 0x58, 0x88, 0x28,
	0x8c, 0xb1, 0x20, 0xcd, 0x92, 0x4a, 0x56, 0xbc, 0x19, 0xc4, 0x76, 0x00, 0x1d, 0x5e, 0x42, 0xcf,
	0x7e, 0x02, 0x37, 0xe6, 0x3a, 0x30, 0x5d, 0xa3, 0xbb, 0x70, 0x35, 0xed, 0x3c, 0x25, 0xd4, 0x7a,
	0x1b, 0xce, 0xb4, 0xeb, 0xe4, 0xc9, 0x23, 0x9d, 0xf0, 0x4c, 0xde, 0x7e, 0x0c, 0xf5, 0xc3, 0xff,
	0xe1, 0x7f, 0xb1, 0xe0, 0xfa, 0x33, 0xc2, 0x48, 0xac, 0xb1, 0x7f, 0xce, 0xbf, 0x0f, 0x6b, 0x23,
	0x2a, 0x64, 0x4c, 0x87, 0x89, 0x24, 0xa3, 0xd4, 0x80, 0xb5, 0x5e, 0x47, 0x8b, 0xe7, 0x1a, 0xfb,
	0xe7, 0xe9, 0x17, 0xe4, 0x6c, 0x80, 0x63, 0x3c, 0x11, 0xcf, 0xaf, 0x78, 0xb3, 0xb4, 0x39, 0x17,
	0x97, 0xe6, 0x5d, 0xec, 0xaf, 0x40, 0xd9, 0x10, 0x6d, 0x0e, 0xdb, 0x7f, 0x13, 0x46, 0x36, 0x54,
	0x22, 0x1c, 0x4b, 0xea, 0xd3, 0x08, 0x33, 0x29, 0xd2, 0x76, 0xab, 0x5e, 0x01, 0x43, 0x0f, 0x60,
	0x43, 0xd0, 0x80, 0x51, 0x16, 0x9c, 0xc8, 0x50, 0xad, 0x45, 0xc8, 0xc7, 0xa6, 0xf3, 0xaa, 0xb7,
	0x9e, 0x25, 0x5e, 0xe5, 0xb8, 0xfd, 0xd5, 0x82, 0xf5, 0x73, 0x3b, 0x2e, 0x69, 0xa6, 0x36, 0x6e,
	0x42, 0x84, 0x50, 0x9b, 0x9a, 0x16, 0x50, 0xc6, 0x65, 0x21, 0xda, 0x51, 0x23, 0x27, 0xc3, 0x31,
	0xf5, 0x4f, 0x4e, 0xc9, 0x59, 0x36, 0xf2, 0xaa, 0x41, 0xd4, 0x34, 0xe8, 0xe1, 0xdc, 0x1c, 0xcb,
	0x9d, 0x25, 0x65, 0x6c, 0x45, 0x17, 0x3a, 0xc8, 0x76, 0xb6, 0x38, 0x55, 0xef, 0x5b, 0x09, 0x6a,
	0xd9, 0xa5, 0xbf, 0x34, 0x6f, 0x03, 0xbd, 0x83, 0xb2, 0x59, 0x26, 0xd4, 0xd4, 0xc4, 0x45, 0xab,
	0xdd, 0x6e, 0x2d, 0xc8, 0x98, 0x41, 0xec, 0xdb, 0x1f, 0x7f, 0xfe, 0xfa, 0x5c, 0xda, 0x42, 0x2d,
	0x77, 0xda, 0x75, 0x8b, 0xcf, 0xce, 0x4d, 0x8c, 0xee, 0x1b, 0x58, 0xd6, 0xcb, 0x86, 0x6e, 0x6a,
	0x95, 0x8b, 0x8b, 0xde, 0xde, 0xbc, 0x80, 0x67, 0xda, 0xb7, 0x52, 0xed, 0x16, 0xda, 0x5c, 0xa0,
	0x9d, 0x2a, 0x1f, 0xc3, 0x4a, 0x6e, 0x3b, 0xaa, 0xcf, 0xee, 0x53, 0x2e, 0xdd, 0x28, 0x82, 0x99,
	0xee, 0x9d, 0x54, 0x77, 0xc7, 0xde, 0x5a, 0xa0, 0x1b, 0x64, 0x87, 0xfb, 0x9f, 0x2c, 0xd8, 0xf5,
	0xf9, 0xc4, 0xf9, 0x40, 0xf0, 0x78, 0x24, 0x89, 0x1f, 0x3a, 0x44, 0x86, 0x3d, 0x7d, 0xf5, 0x2a,
	0x1f, 0x51, 0x25, 0xdc, 0xaf, 0x17, 0xad, 0x1c, 0xe8, 0xef, 0x61, 0x60, 0x1d, 0xdf, 0x0f, 0xa8,
	0x0c, 0x93, 0xa1, 0xa3, 0xd8, 0xee, 0x1f, 0xb6, 0xab, 0xd9, 0x7b, 0x86, 0xbe, 0xa7, 0x7f, 0x9f,
	0x68, 0xa8, 0xaa, 0x7f, 0x2f, 0x55, 0x0f, 0x14, 0x7e, 0x94, 0xc2, 0x4a, 0xf2, 0xc7, 0x6c, 0xfc,
	0x76, 0xda, 0x1d, 0x96, 0xd3, 0x3f, 0xe7, 0xd1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0xbe,
	0x87, 0xb0, 0xd2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountManagerClient is the client API for AccountManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountManagerClient interface {
	Unlock(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*UnlockAccountResponse, error)
	Lock(ctx context.Context, in *LockAccountRequest, opts ...grpc.CallOption) (*LockAccountResponse, error)
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type accountManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountManagerClient(cc grpc.ClientConnInterface) AccountManagerClient {
	return &accountManagerClient{cc}
}

func (c *accountManagerClient) Unlock(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*UnlockAccountResponse, error) {
	out := new(UnlockAccountResponse)
	err := c.cc.Invoke(ctx, "/v1.AccountManager/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) Lock(ctx context.Context, in *LockAccountRequest, opts ...grpc.CallOption) (*LockAccountResponse, error) {
	out := new(LockAccountResponse)
	err := c.cc.Invoke(ctx, "/v1.AccountManager/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagerClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, "/v1.AccountManager/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountManagerServer is the server API for AccountManager service.
type AccountManagerServer interface {
	Unlock(context.Context, *UnlockAccountRequest) (*UnlockAccountResponse, error)
	Lock(context.Context, *LockAccountRequest) (*LockAccountResponse, error)
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
}

// UnimplementedAccountManagerServer can be embedded to have forward compatible implementations.
type UnimplementedAccountManagerServer struct {
}

func (*UnimplementedAccountManagerServer) Unlock(ctx context.Context, req *UnlockAccountRequest) (*UnlockAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (*UnimplementedAccountManagerServer) Lock(ctx context.Context, req *LockAccountRequest) (*LockAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}
func (*UnimplementedAccountManagerServer) Generate(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}

func RegisterAccountManagerServer(s *grpc.Server, srv AccountManagerServer) {
	s.RegisterService(&_AccountManager_serviceDesc, srv)
}

func _AccountManager_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AccountManager/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).Unlock(ctx, req.(*UnlockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AccountManager/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).Lock(ctx, req.(*LockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManager_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagerServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AccountManager/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagerServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AccountManager",
	HandlerType: (*AccountManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unlock",
			Handler:    _AccountManager_Unlock_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _AccountManager_Lock_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _AccountManager_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accountmanager.proto",
}
