// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dkg.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrepareRequest struct {
	// account is the name of the account.
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// threshold is the number of participants required to generate a valid signature.
	Threshold uint32 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// participants contains the endpoints of all participants.
	Participants []*Endpoint `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	// passphrase is the passphrase of the account.
	Passphrase           []byte   `protobuf:"bytes,4,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareRequest) Reset()         { *m = PrepareRequest{} }
func (m *PrepareRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareRequest) ProtoMessage()    {}
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_584d508ed20653c0, []int{0}
}

func (m *PrepareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareRequest.Unmarshal(m, b)
}
func (m *PrepareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareRequest.Marshal(b, m, deterministic)
}
func (m *PrepareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareRequest.Merge(m, src)
}
func (m *PrepareRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareRequest.Size(m)
}
func (m *PrepareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareRequest proto.InternalMessageInfo

func (m *PrepareRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PrepareRequest) GetThreshold() uint32 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *PrepareRequest) GetParticipants() []*Endpoint {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *PrepareRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type ExecuteRequest struct {
	// account is the name of the account.
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_584d508ed20653c0, []int{1}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

func (m *ExecuteRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type CommitRequest struct {
	// account is the name of the account.
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// confirmation data is data used to generate the confirmation signature.
	ConfirmationData     []byte   `protobuf:"bytes,2,opt,name=confirmation_data,json=confirmationData,proto3" json:"confirmation_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_584d508ed20653c0, []int{2}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CommitRequest) GetConfirmationData() []byte {
	if m != nil {
		return m.ConfirmationData
	}
	return nil
}

type CommitResponse struct {
	// public_key is the key generated by the process.
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// confirmation_signature is the signature generated by the individual secret key.
	ConfirmationSignature []byte   `protobuf:"bytes,2,opt,name=confirmation_signature,json=confirmationSignature,proto3" json:"confirmation_signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CommitResponse) Reset()         { *m = CommitResponse{} }
func (m *CommitResponse) String() string { return proto.CompactTextString(m) }
func (*CommitResponse) ProtoMessage()    {}
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_584d508ed20653c0, []int{3}
}

func (m *CommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResponse.Unmarshal(m, b)
}
func (m *CommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResponse.Marshal(b, m, deterministic)
}
func (m *CommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResponse.Merge(m, src)
}
func (m *CommitResponse) XXX_Size() int {
	return xxx_messageInfo_CommitResponse.Size(m)
}
func (m *CommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResponse proto.InternalMessageInfo

func (m *CommitResponse) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *CommitResponse) GetConfirmationSignature() []byte {
	if m != nil {
		return m.ConfirmationSignature
	}
	return nil
}

type AbortRequest struct {
	// account is the name of the account.
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AbortRequest) Reset()         { *m = AbortRequest{} }
func (m *AbortRequest) String() string { return proto.CompactTextString(m) }
func (*AbortRequest) ProtoMessage()    {}
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_584d508ed20653c0, []int{4}
}

func (m *AbortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AbortRequest.Unmarshal(m, b)
}
func (m *AbortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AbortRequest.Marshal(b, m, deterministic)
}
func (m *AbortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbortRequest.Merge(m, src)
}
func (m *AbortRequest) XXX_Size() int {
	return xxx_messageInfo_AbortRequest.Size(m)
}
func (m *AbortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AbortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AbortRequest proto.InternalMessageInfo

func (m *AbortRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// ContributeRequest is sent by each part to all other parties with a contribution.
type ContributeRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Secret               []byte   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	VerificationVector   [][]byte `protobuf:"bytes,3,rep,name=verification_vector,json=verificationVector,proto3" json:"verification_vector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContributeRequest) Reset()         { *m = ContributeRequest{} }
func (m *ContributeRequest) String() string { return proto.CompactTextString(m) }
func (*ContributeRequest) ProtoMessage()    {}
func (*ContributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_584d508ed20653c0, []int{5}
}

func (m *ContributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContributeRequest.Unmarshal(m, b)
}
func (m *ContributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContributeRequest.Marshal(b, m, deterministic)
}
func (m *ContributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContributeRequest.Merge(m, src)
}
func (m *ContributeRequest) XXX_Size() int {
	return xxx_messageInfo_ContributeRequest.Size(m)
}
func (m *ContributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContributeRequest proto.InternalMessageInfo

func (m *ContributeRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ContributeRequest) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *ContributeRequest) GetVerificationVector() [][]byte {
	if m != nil {
		return m.VerificationVector
	}
	return nil
}

// ContributeResponse receives the contribution from a participant.
type ContributeResponse struct {
	Secret               []byte   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	VerificationVector   [][]byte `protobuf:"bytes,2,rep,name=verification_vector,json=verificationVector,proto3" json:"verification_vector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContributeResponse) Reset()         { *m = ContributeResponse{} }
func (m *ContributeResponse) String() string { return proto.CompactTextString(m) }
func (*ContributeResponse) ProtoMessage()    {}
func (*ContributeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_584d508ed20653c0, []int{6}
}

func (m *ContributeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContributeResponse.Unmarshal(m, b)
}
func (m *ContributeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContributeResponse.Marshal(b, m, deterministic)
}
func (m *ContributeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContributeResponse.Merge(m, src)
}
func (m *ContributeResponse) XXX_Size() int {
	return xxx_messageInfo_ContributeResponse.Size(m)
}
func (m *ContributeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContributeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContributeResponse proto.InternalMessageInfo

func (m *ContributeResponse) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *ContributeResponse) GetVerificationVector() [][]byte {
	if m != nil {
		return m.VerificationVector
	}
	return nil
}

func init() {
	proto.RegisterType((*PrepareRequest)(nil), "v1.PrepareRequest")
	proto.RegisterType((*ExecuteRequest)(nil), "v1.ExecuteRequest")
	proto.RegisterType((*CommitRequest)(nil), "v1.CommitRequest")
	proto.RegisterType((*CommitResponse)(nil), "v1.CommitResponse")
	proto.RegisterType((*AbortRequest)(nil), "v1.AbortRequest")
	proto.RegisterType((*ContributeRequest)(nil), "v1.ContributeRequest")
	proto.RegisterType((*ContributeResponse)(nil), "v1.ContributeResponse")
}

func init() {
	proto.RegisterFile("dkg.proto", fileDescriptor_584d508ed20653c0)
}

var fileDescriptor_584d508ed20653c0 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0x24, 0x09, 0xa4, 0xe4, 0xc3, 0x89, 0x9a, 0x45, 0x8d, 0xa2, 0x00, 0x55, 0xe5, 0x53, 0x54,
	0x54, 0x9b, 0xa4, 0x42, 0x9c, 0x38, 0xd0, 0x36, 0xe2, 0xd0, 0x4b, 0xe4, 0x4a, 0x3d, 0x20, 0x50,
	0xb5, 0xde, 0x7c, 0x89, 0x57, 0x4d, 0xbc, 0x66, 0xbd, 0x36, 0xcd, 0xab, 0x70, 0xe0, 0x01, 0x78,
	0x14, 0x9e, 0x8a, 0xb5, 0xd7, 0x21, 0x76, 0x25, 0x9a, 0x1e, 0x77, 0xbe, 0x9d, 0x99, 0xef, 0x67,
	0xa0, 0x35, 0xbb, 0x5d, 0x38, 0x91, 0x14, 0x4a, 0x90, 0x7a, 0x3a, 0x1a, 0xbc, 0x5a, 0x08, 0xb1,
	0x58, 0xa2, 0x9b, 0x23, 0x7e, 0x32, 0x77, 0x71, 0x15, 0xa9, 0xb5, 0xf9, 0x30, 0xe8, 0x60, 0x38,
	0x8b, 0x04, 0x0f, 0x95, 0x79, 0xdb, 0x3f, 0x6b, 0xd0, 0x99, 0x4a, 0x8c, 0xa8, 0x44, 0x0f, 0xbf,
	0x27, 0x18, 0x2b, 0xd2, 0x87, 0x3d, 0xca, 0x98, 0x48, 0x42, 0xd5, 0xaf, 0x1d, 0xd5, 0x86, 0x2d,
	0x6f, 0xf3, 0x24, 0xaf, 0xa1, 0xa5, 0x02, 0x89, 0x71, 0x20, 0x96, 0xb3, 0x7e, 0x5d, 0xd7, 0xda,
	0xde, 0x16, 0x20, 0xef, 0xc0, 0xd2, 0x32, 0x8a, 0x33, 0x1e, 0xd1, 0x50, 0xc5, 0xfd, 0xc6, 0x51,
	0x63, 0xf8, 0x62, 0x6c, 0x39, 0xe9, 0xc8, 0x99, 0x14, 0xa6, 0x5e, 0xe5, 0x07, 0x39, 0x04, 0x88,
	0x68, 0x1c, 0x47, 0x81, 0xa4, 0x31, 0xf6, 0x9f, 0x6a, 0x41, 0xcb, 0x2b, 0x21, 0xf6, 0x31, 0x74,
	0x26, 0x77, 0xc8, 0x12, 0xb5, 0xbb, 0x37, 0xfb, 0x1a, 0xda, 0xe7, 0x62, 0xb5, 0xe2, 0x6a, 0xf7,
	0x18, 0x6f, 0xa1, 0xcb, 0x44, 0x38, 0xe7, 0x72, 0x45, 0x15, 0x17, 0xe1, 0xcd, 0x8c, 0x2a, 0x9a,
	0x8f, 0x63, 0x79, 0xfb, 0xe5, 0xc2, 0x85, 0xc6, 0xed, 0x39, 0x74, 0x36, 0xba, 0x71, 0x24, 0xc2,
	0x18, 0xc9, 0x1b, 0xdd, 0x75, 0xe2, 0x2f, 0x39, 0xbb, 0xb9, 0xc5, 0x75, 0xae, 0x6d, 0x79, 0x2d,
	0x83, 0x5c, 0xe2, 0x9a, 0xbc, 0x87, 0x5e, 0x45, 0x3d, 0xe6, 0x8b, 0x90, 0xaa, 0x44, 0x62, 0x61,
	0x71, 0x50, 0xae, 0x5e, 0x6d, 0x8a, 0xf6, 0x10, 0xac, 0x4f, 0xbe, 0x90, 0xbb, 0xdb, 0xb7, 0x53,
	0xe8, 0x9e, 0x8b, 0x50, 0x49, 0xee, 0x3f, 0x66, 0x31, 0xa4, 0x07, 0xcd, 0x18, 0x99, 0x44, 0x55,
	0xf8, 0x17, 0x2f, 0xe2, 0xc2, 0xcb, 0x14, 0x25, 0x9f, 0x73, 0x66, 0xfa, 0x4c, 0x91, 0x29, 0x21,
	0xf3, 0xab, 0x59, 0x1e, 0x29, 0x97, 0xae, 0xf3, 0x8a, 0xfd, 0x0d, 0x48, 0xd9, 0xb7, 0xd8, 0xc6,
	0x56, 0xbe, 0xf6, 0x18, 0xf9, 0xfa, 0xff, 0xe4, 0xc7, 0xbf, 0xea, 0xd0, 0xb8, 0xb8, 0xfc, 0x4c,
	0x3e, 0xc0, 0x5e, 0x11, 0x48, 0x42, 0xb2, 0xec, 0x54, 0xd3, 0x39, 0xe8, 0x39, 0x26, 0xde, 0xce,
	0x26, 0xde, 0xce, 0x24, 0x8b, 0xb7, 0xfd, 0x24, 0x23, 0x16, 0x69, 0x31, 0xc4, 0x6a, 0x74, 0x1e,
	0x20, 0x8e, 0xa0, 0x69, 0x4e, 0x4c, 0xba, 0x19, 0xaf, 0x12, 0xa3, 0x01, 0x29, 0x43, 0x66, 0x66,
	0x4d, 0x39, 0x85, 0x67, 0xf9, 0xb5, 0xc8, 0x7e, 0x56, 0x2e, 0x1f, 0xee, 0x01, 0x9f, 0x8f, 0x00,
	0xdb, 0x05, 0x92, 0x03, 0x23, 0x7c, 0xef, 0x90, 0x9a, 0x7e, 0x0f, 0xde, 0x78, 0x9e, 0xdd, 0xc1,
	0x21, 0x13, 0x2b, 0xe7, 0x07, 0xd2, 0xe5, 0x4c, 0x21, 0x0b, 0x1c, 0x54, 0xc1, 0x38, 0x4b, 0x17,
	0x4a, 0x1a, 0x71, 0x4d, 0x3b, 0x7b, 0xae, 0xf7, 0x37, 0xcd, 0x5c, 0xa7, 0xb5, 0x2f, 0xc7, 0x0b,
	0xae, 0x82, 0xc4, 0x77, 0x34, 0xc5, 0xfd, 0x47, 0x71, 0x33, 0xca, 0x89, 0xe1, 0x9c, 0x68, 0x92,
	0x1b, 0xf9, 0x6e, 0x3a, 0xfa, 0x5d, 0x6f, 0x4f, 0x34, 0x7e, 0x95, 0xc3, 0x5a, 0xe7, 0x4f, 0xf9,
	0xfd, 0x35, 0x1d, 0xf9, 0xcd, 0x7c, 0x94, 0xd3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x32, 0x63,
	0xe2, 0x5b, 0x69, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DKGClient is the client API for DKG service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DKGClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Contribute(ctx context.Context, in *ContributeRequest, opts ...grpc.CallOption) (*ContributeResponse, error)
}

type dKGClient struct {
	cc grpc.ClientConnInterface
}

func NewDKGClient(cc grpc.ClientConnInterface) DKGClient {
	return &dKGClient{cc}
}

func (c *dKGClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.DKG/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKGClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.DKG/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKGClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, "/v1.DKG/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKGClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/v1.DKG/Abort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dKGClient) Contribute(ctx context.Context, in *ContributeRequest, opts ...grpc.CallOption) (*ContributeResponse, error) {
	out := new(ContributeResponse)
	err := c.cc.Invoke(ctx, "/v1.DKG/Contribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DKGServer is the server API for DKG service.
type DKGServer interface {
	Prepare(context.Context, *PrepareRequest) (*empty.Empty, error)
	Execute(context.Context, *ExecuteRequest) (*empty.Empty, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	Abort(context.Context, *AbortRequest) (*empty.Empty, error)
	Contribute(context.Context, *ContributeRequest) (*ContributeResponse, error)
}

// UnimplementedDKGServer can be embedded to have forward compatible implementations.
type UnimplementedDKGServer struct {
}

func (*UnimplementedDKGServer) Prepare(ctx context.Context, req *PrepareRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (*UnimplementedDKGServer) Execute(ctx context.Context, req *ExecuteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedDKGServer) Commit(ctx context.Context, req *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (*UnimplementedDKGServer) Abort(ctx context.Context, req *AbortRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (*UnimplementedDKGServer) Contribute(ctx context.Context, req *ContributeRequest) (*ContributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Contribute not implemented")
}

func RegisterDKGServer(s *grpc.Server, srv DKGServer) {
	s.RegisterService(&_DKG_serviceDesc, srv)
}

func _DKG_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKGServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DKG/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKGServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKG_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKGServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DKG/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKGServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKG_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKGServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DKG/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKGServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKG_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKGServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DKG/Abort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKGServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DKG_Contribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DKGServer).Contribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DKG/Contribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DKGServer).Contribute(ctx, req.(*ContributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DKG_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DKG",
	HandlerType: (*DKGServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _DKG_Prepare_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _DKG_Execute_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _DKG_Commit_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _DKG_Abort_Handler,
		},
		{
			MethodName: "Contribute",
			Handler:    _DKG_Contribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dkg.proto",
}
