// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eth2.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	eth2.proto

It has these top-level messages:
	AttestationData
	Checkpoint
	BeaconBlockHeader
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AttestationData is defined at https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#attestationdata
type AttestationData struct {
	Slot            uint64      `protobuf:"varint,1,opt,name=slot" json:"slot,omitempty"`
	CommitteeIndex  uint64      `protobuf:"varint,2,opt,name=committee_index,json=committeeIndex" json:"committee_index,omitempty"`
	BeaconBlockRoot []byte      `protobuf:"bytes,3,opt,name=beacon_block_root,json=beaconBlockRoot,proto3" json:"beacon_block_root,omitempty"`
	Source          *Checkpoint `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	Target          *Checkpoint `protobuf:"bytes,5,opt,name=target" json:"target,omitempty"`
}

func (m *AttestationData) Reset()                    { *m = AttestationData{} }
func (m *AttestationData) String() string            { return proto.CompactTextString(m) }
func (*AttestationData) ProtoMessage()               {}
func (*AttestationData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AttestationData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationData) GetCommitteeIndex() uint64 {
	if m != nil {
		return m.CommitteeIndex
	}
	return 0
}

func (m *AttestationData) GetBeaconBlockRoot() []byte {
	if m != nil {
		return m.BeaconBlockRoot
	}
	return nil
}

func (m *AttestationData) GetSource() *Checkpoint {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *AttestationData) GetTarget() *Checkpoint {
	if m != nil {
		return m.Target
	}
	return nil
}

// Checkpoint is defined at https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#checkpoint
type Checkpoint struct {
	Epoch uint64 `protobuf:"varint,1,opt,name=epoch" json:"epoch,omitempty"`
	Root  []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
}

func (m *Checkpoint) Reset()                    { *m = Checkpoint{} }
func (m *Checkpoint) String() string            { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()               {}
func (*Checkpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Checkpoint) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Checkpoint) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

// BeaconBlockheader is defined at https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#beaconblockheader
type BeaconBlockHeader struct {
	Slot       uint64 `protobuf:"varint,1,opt,name=slot" json:"slot,omitempty"`
	ParentRoot []byte `protobuf:"bytes,2,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	StateRoot  []byte `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	BodyRoot   []byte `protobuf:"bytes,4,opt,name=body_root,json=bodyRoot,proto3" json:"body_root,omitempty"`
}

func (m *BeaconBlockHeader) Reset()                    { *m = BeaconBlockHeader{} }
func (m *BeaconBlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BeaconBlockHeader) ProtoMessage()               {}
func (*BeaconBlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BeaconBlockHeader) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *BeaconBlockHeader) GetParentRoot() []byte {
	if m != nil {
		return m.ParentRoot
	}
	return nil
}

func (m *BeaconBlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BeaconBlockHeader) GetBodyRoot() []byte {
	if m != nil {
		return m.BodyRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*AttestationData)(nil), "v1.AttestationData")
	proto.RegisterType((*Checkpoint)(nil), "v1.Checkpoint")
	proto.RegisterType((*BeaconBlockHeader)(nil), "v1.BeaconBlockHeader")
}

func init() { proto.RegisterFile("eth2.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xbe, 0xb4, 0x7c, 0x9d, 0x6a, 0x4b, 0x83, 0x87, 0x80, 0xa8, 0xa5, 0x07, 0x2d,
	0x1e, 0x16, 0x52, 0xc1, 0xbb, 0x51, 0x41, 0x0f, 0x42, 0x89, 0x57, 0x21, 0x6c, 0x36, 0x43, 0x13,
	0xda, 0x66, 0xc2, 0x66, 0x8c, 0x7a, 0xf7, 0x69, 0x7c, 0x94, 0x3e, 0x95, 0xec, 0xa6, 0xd8, 0x1e,
	0x7a, 0xdb, 0xf9, 0xfd, 0x86, 0x65, 0xfe, 0x33, 0x00, 0xc8, 0xf9, 0x4c, 0x54, 0x9a, 0x98, 0x7c,
	0xb7, 0x09, 0x27, 0x1b, 0x07, 0x86, 0x77, 0xcc, 0x58, 0xb3, 0xe4, 0x82, 0xca, 0x07, 0xc9, 0xd2,
	0xf7, 0xc1, 0xab, 0x57, 0xc4, 0x81, 0x33, 0x76, 0xa6, 0x5e, 0x6c, 0xdf, 0xfe, 0x15, 0x0c, 0x15,
	0xad, 0xd7, 0x05, 0x33, 0x62, 0x52, 0x94, 0x19, 0x7e, 0x06, 0xae, 0xd5, 0x83, 0x3f, 0xfc, 0x6c,
	0xa8, 0x7f, 0x0d, 0xa3, 0x14, 0xa5, 0xa2, 0x32, 0x49, 0x57, 0xa4, 0x96, 0x89, 0x26, 0xe2, 0xe0,
	0xdf, 0xd8, 0x99, 0x1e, 0xc5, 0xc3, 0x56, 0x44, 0x86, 0xc7, 0x44, 0xec, 0x5f, 0x42, 0xb7, 0xa6,
	0x77, 0xad, 0x30, 0xf0, 0xc6, 0xce, 0xb4, 0x3f, 0x1b, 0x88, 0x26, 0x14, 0xf7, 0x39, 0xaa, 0x65,
	0x45, 0x45, 0xc9, 0xf1, 0xd6, 0x9a, 0x3e, 0x96, 0x7a, 0x81, 0x1c, 0x74, 0x0e, 0xf7, 0xb5, 0x76,
	0x72, 0x0b, 0xb0, 0xa3, 0xfe, 0x09, 0x74, 0xb0, 0x22, 0x95, 0x6f, 0x73, 0xb4, 0x85, 0x09, 0x67,
	0x47, 0x72, 0xed, 0x48, 0xf6, 0x3d, 0xf9, 0x76, 0x60, 0x14, 0xed, 0x66, 0x7b, 0x42, 0x99, 0xa1,
	0x3e, 0xb8, 0x86, 0x0b, 0xe8, 0x57, 0x52, 0x63, 0xc9, 0xc9, 0xde, 0x27, 0xd0, 0x22, 0x1b, 0xe9,
	0x0c, 0xc0, 0xac, 0x12, 0xf7, 0x73, 0xf7, 0x2c, 0xb1, 0xfa, 0x14, 0x7a, 0x29, 0x65, 0x5f, 0xad,
	0xf5, 0xac, 0xfd, 0x6f, 0x80, 0x91, 0xd1, 0x0b, 0x9c, 0x2b, 0x5a, 0x8b, 0x0f, 0x94, 0xab, 0x8c,
	0x51, 0xe5, 0xc2, 0xdc, 0xaa, 0x2e, 0x16, 0x25, 0x6a, 0x59, 0x15, 0xa2, 0x09, 0xa3, 0xde, 0x23,
	0xe7, 0xb3, 0xb9, 0x39, 0xde, 0xdc, 0xf9, 0x71, 0x8f, 0x4d, 0xf5, 0x6a, 0xbd, 0x68, 0xc2, 0xcd,
	0x7e, 0xfd, 0xd6, 0x84, 0x69, 0xd7, 0x5e, 0xf9, 0xe6, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x2a,
	0x95, 0x5a, 0xf3, 0x01, 0x00, 0x00,
}
