// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eth2.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AttestationData is defined at https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#attestationdata
type AttestationData struct {
	Slot                 uint64      `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	CommitteeIndex       uint64      `protobuf:"varint,2,opt,name=committee_index,json=committeeIndex,proto3" json:"committee_index,omitempty"`
	BeaconBlockRoot      []byte      `protobuf:"bytes,3,opt,name=beacon_block_root,json=beaconBlockRoot,proto3" json:"beacon_block_root,omitempty"`
	Source               *Checkpoint `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Target               *Checkpoint `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AttestationData) Reset()         { *m = AttestationData{} }
func (m *AttestationData) String() string { return proto.CompactTextString(m) }
func (*AttestationData) ProtoMessage()    {}
func (*AttestationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52217a1e941062, []int{0}
}

func (m *AttestationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationData.Unmarshal(m, b)
}
func (m *AttestationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationData.Marshal(b, m, deterministic)
}
func (m *AttestationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationData.Merge(m, src)
}
func (m *AttestationData) XXX_Size() int {
	return xxx_messageInfo_AttestationData.Size(m)
}
func (m *AttestationData) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationData.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationData proto.InternalMessageInfo

func (m *AttestationData) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *AttestationData) GetCommitteeIndex() uint64 {
	if m != nil {
		return m.CommitteeIndex
	}
	return 0
}

func (m *AttestationData) GetBeaconBlockRoot() []byte {
	if m != nil {
		return m.BeaconBlockRoot
	}
	return nil
}

func (m *AttestationData) GetSource() *Checkpoint {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *AttestationData) GetTarget() *Checkpoint {
	if m != nil {
		return m.Target
	}
	return nil
}

// Checkpoint is defined at https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#checkpoint
type Checkpoint struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Root                 []byte   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52217a1e941062, []int{1}
}

func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkpoint.Unmarshal(m, b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return xxx_messageInfo_Checkpoint.Size(m)
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Checkpoint) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

// BeaconBlockheader is defined at https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#beaconblockheader
type BeaconBlockHeader struct {
	Slot                 uint64   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ParentRoot           []byte   `protobuf:"bytes,2,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	StateRoot            []byte   `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	BodyRoot             []byte   `protobuf:"bytes,4,opt,name=body_root,json=bodyRoot,proto3" json:"body_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeaconBlockHeader) Reset()         { *m = BeaconBlockHeader{} }
func (m *BeaconBlockHeader) String() string { return proto.CompactTextString(m) }
func (*BeaconBlockHeader) ProtoMessage()    {}
func (*BeaconBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c52217a1e941062, []int{2}
}

func (m *BeaconBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconBlockHeader.Unmarshal(m, b)
}
func (m *BeaconBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconBlockHeader.Marshal(b, m, deterministic)
}
func (m *BeaconBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconBlockHeader.Merge(m, src)
}
func (m *BeaconBlockHeader) XXX_Size() int {
	return xxx_messageInfo_BeaconBlockHeader.Size(m)
}
func (m *BeaconBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconBlockHeader proto.InternalMessageInfo

func (m *BeaconBlockHeader) GetSlot() uint64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *BeaconBlockHeader) GetParentRoot() []byte {
	if m != nil {
		return m.ParentRoot
	}
	return nil
}

func (m *BeaconBlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BeaconBlockHeader) GetBodyRoot() []byte {
	if m != nil {
		return m.BodyRoot
	}
	return nil
}

func init() {
	proto.RegisterType((*AttestationData)(nil), "v1.AttestationData")
	proto.RegisterType((*Checkpoint)(nil), "v1.Checkpoint")
	proto.RegisterType((*BeaconBlockHeader)(nil), "v1.BeaconBlockHeader")
}

func init() {
	proto.RegisterFile("eth2.proto", fileDescriptor_5c52217a1e941062)
}

var fileDescriptor_5c52217a1e941062 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0xea, 0xd3, 0x40,
	0x10, 0xc6, 0x49, 0x4c, 0x8b, 0x9d, 0x6a, 0x4b, 0x83, 0x87, 0x80, 0xa8, 0xa5, 0x07, 0x2d, 0x85,
	0x6e, 0x48, 0x05, 0xef, 0x46, 0x05, 0xbd, 0x95, 0x78, 0x13, 0x21, 0x6c, 0x36, 0x43, 0xb3, 0xb4,
	0xc9, 0x84, 0x64, 0x1a, 0xed, 0xdd, 0xa7, 0xf1, 0x51, 0xfa, 0x54, 0x7f, 0x76, 0x53, 0xda, 0x1e,
	0x7a, 0xdb, 0xfd, 0xfd, 0xf6, 0x0b, 0xf3, 0xed, 0x06, 0x00, 0xb9, 0xd8, 0x88, 0xba, 0x21, 0x26,
	0xdf, 0xed, 0xa2, 0xc5, 0xd9, 0x81, 0xe9, 0x67, 0x66, 0x6c, 0x59, 0xb2, 0xa6, 0xea, 0xab, 0x64,
	0xe9, 0xfb, 0xe0, 0xb5, 0x07, 0xe2, 0xc0, 0x99, 0x3b, 0x4b, 0x2f, 0xb1, 0x6b, 0xff, 0x03, 0x4c,
	0x15, 0x95, 0xa5, 0x66, 0x46, 0x4c, 0x75, 0x95, 0xe3, 0xdf, 0xc0, 0xb5, 0x7a, 0x72, 0xc5, 0x3f,
	0x0c, 0xf5, 0x57, 0x30, 0xcb, 0x50, 0x2a, 0xaa, 0xd2, 0xec, 0x40, 0x6a, 0x9f, 0x36, 0x44, 0x1c,
	0x3c, 0x9b, 0x3b, 0xcb, 0x17, 0xc9, 0xb4, 0x17, 0xb1, 0xe1, 0x09, 0x11, 0xfb, 0xef, 0x61, 0xd8,
	0xd2, 0xb1, 0x51, 0x18, 0x78, 0x73, 0x67, 0x39, 0xde, 0x4c, 0x44, 0x17, 0x89, 0x2f, 0x05, 0xaa,
	0x7d, 0x4d, 0xba, 0xe2, 0xe4, 0x62, 0xcd, 0x39, 0x96, 0xcd, 0x0e, 0x39, 0x18, 0x3c, 0x3e, 0xd7,
	0xdb, 0xc5, 0x27, 0x80, 0x1b, 0xf5, 0x5f, 0xc1, 0x00, 0x6b, 0x52, 0xc5, 0xa5, 0x47, 0xbf, 0x31,
	0xe5, 0xec, 0x48, 0xae, 0x1d, 0xc9, 0xae, 0x17, 0xff, 0x1c, 0x98, 0xc5, 0xb7, 0xd9, 0xbe, 0xa3,
	0xcc, 0xb1, 0x79, 0x78, 0x0d, 0xef, 0x60, 0x5c, 0xcb, 0x06, 0x2b, 0x4e, 0xef, 0x3e, 0x02, 0x3d,
	0xb2, 0x95, 0xde, 0x00, 0x98, 0xab, 0xc4, 0xfb, 0xde, 0x23, 0x4b, 0xac, 0x7e, 0x0d, 0xa3, 0x8c,
	0xf2, 0x53, 0x6f, 0x3d, 0x6b, 0x9f, 0x1b, 0x60, 0x64, 0x7c, 0x82, 0xb7, 0x8a, 0x4a, 0xf1, 0x07,
	0xe5, 0x21, 0x67, 0x54, 0x85, 0x30, 0x6f, 0xd5, 0xea, 0x5d, 0x85, 0x8d, 0xac, 0xb5, 0xe8, 0xa2,
	0x78, 0xf4, 0x8d, 0x8b, 0xcd, 0xd6, 0x3c, 0xde, 0xd6, 0xf9, 0xb5, 0xda, 0x69, 0x2e, 0x8e, 0x99,
	0x50, 0x54, 0x86, 0xd7, 0x4c, 0x68, 0x32, 0xeb, 0x3e, 0xb4, 0x96, 0xb5, 0x0e, 0xeb, 0x2c, 0xec,
	0xa2, 0xff, 0xee, 0x4b, 0x93, 0xfc, 0x69, 0xb1, 0xe8, 0xa2, 0xf3, 0xfd, 0xfe, 0x77, 0x17, 0x65,
	0x43, 0xfb, 0x47, 0x7c, 0x7c, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xda, 0x1e, 0xc3, 0x1f, 0x02,
	0x00, 0x00,
}
