// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lister.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	lister.proto

It has these top-level messages:
	ListAccountsRequest
	ListAccountsResponse
	Account
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import v11 "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListAccountsRequest struct {
	Paths []string `protobuf:"bytes,1,rep,name=paths" json:"paths,omitempty"`
}

func (m *ListAccountsRequest) Reset()                    { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()               {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListAccountsRequest) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type ListAccountsResponse struct {
	State    v11.ResponseState `protobuf:"varint,1,opt,name=state,enum=v1.ResponseState" json:"state,omitempty"`
	Accounts []*Account        `protobuf:"bytes,2,rep,name=Accounts" json:"Accounts,omitempty"`
}

func (m *ListAccountsResponse) Reset()                    { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()               {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListAccountsResponse) GetState() v11.ResponseState {
	if m != nil {
		return m.State
	}
	return v11.ResponseState_UNKNOWN
}

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Account struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*ListAccountsRequest)(nil), "v1.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "v1.ListAccountsResponse")
	proto.RegisterType((*Account)(nil), "v1.Account")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Lister service

type ListerClient interface {
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
}

type listerClient struct {
	cc *grpc.ClientConn
}

func NewListerClient(cc *grpc.ClientConn) ListerClient {
	return &listerClient{cc}
}

func (c *listerClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := grpc.Invoke(ctx, "/v1.Lister/ListAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Lister service

type ListerServer interface {
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
}

func RegisterListerServer(s *grpc.Server, srv ListerServer) {
	s.RegisterService(&_Lister_serviceDesc, srv)
}

func _Lister_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListerServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Lister/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListerServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lister_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Lister",
	HandlerType: (*ListerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAccounts",
			Handler:    _Lister_ListAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lister.proto",
}

func init() { proto.RegisterFile("lister.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x25, 0xe9, 0xd7, 0x7e, 0x76, 0x5a, 0x05, 0xa7, 0x85, 0xc6, 0xe2, 0x4f, 0xc8, 0xa6, 0x01,
	0x61, 0x42, 0xe2, 0xd6, 0x8d, 0x05, 0x57, 0x16, 0x2c, 0xe9, 0x56, 0x90, 0x69, 0xbc, 0x34, 0x83,
	0xe9, 0x4c, 0xcc, 0xdc, 0x46, 0xba, 0xf5, 0x15, 0x7c, 0x0b, 0x1f, 0xc5, 0xad, 0xaf, 0xe0, 0x83,
	0x48, 0x32, 0xad, 0x54, 0x74, 0x95, 0x7b, 0xcf, 0x39, 0x39, 0x73, 0xe6, 0x0c, 0xe9, 0x66, 0x42,
	0x23, 0x14, 0x2c, 0x2f, 0x14, 0x2a, 0x6a, 0x97, 0xe1, 0xf0, 0x78, 0xa1, 0xd4, 0x22, 0x83, 0x80,
	0xe7, 0x22, 0xe0, 0x52, 0x2a, 0xe4, 0x28, 0x94, 0xd4, 0x46, 0x31, 0xec, 0x15, 0xa0, 0x73, 0x25,
	0x35, 0x68, 0xe4, 0x08, 0x06, 0xf4, 0xce, 0x49, 0x6f, 0x22, 0x34, 0x5e, 0x25, 0x89, 0x5a, 0x49,
	0xd4, 0x31, 0x3c, 0xad, 0x40, 0x23, 0xed, 0x93, 0x66, 0xce, 0x31, 0xd5, 0x8e, 0xe5, 0x36, 0xfc,
	0x76, 0x6c, 0x16, 0x2f, 0x25, 0xfd, 0x9f, 0x62, 0xe3, 0x47, 0x47, 0xa4, 0x59, 0x7b, 0x3a, 0x96,
	0x6b, 0xf9, 0x07, 0xd1, 0x21, 0x2b, 0x43, 0xb6, 0x25, 0x67, 0x15, 0x11, 0x1b, 0x9e, 0x8e, 0xc8,
	0xde, 0xf6, 0x67, 0xc7, 0x76, 0x1b, 0x7e, 0x27, 0xea, 0x54, 0xda, 0x0d, 0x16, 0x7f, 0x93, 0xde,
	0x25, 0xf9, 0xbf, 0x99, 0x29, 0x25, 0xff, 0x24, 0x5f, 0x1a, 0xef, 0x76, 0x5c, 0xcf, 0xf4, 0x84,
	0x90, 0x7c, 0x35, 0xcf, 0x44, 0x72, 0xff, 0x08, 0x6b, 0xc7, 0x76, 0x2d, 0xbf, 0x1b, 0xb7, 0x0d,
	0x72, 0x03, 0xeb, 0x28, 0x23, 0xad, 0x49, 0xdd, 0x0d, 0x9d, 0x93, 0xee, 0x6e, 0x62, 0x3a, 0xa8,
	0x8e, 0xfb, 0xe3, 0xc2, 0x43, 0xe7, 0x37, 0x61, 0xf2, 0x7b, 0x67, 0x2f, 0x1f, 0x9f, 0xaf, 0xf6,
	0x11, 0x1d, 0x04, 0x65, 0x18, 0x98, 0xca, 0xeb, 0x0f, 0xdf, 0x08, 0xc7, 0xb7, 0xe4, 0x34, 0x51,
	0x4b, 0xf6, 0x0c, 0x3c, 0x7b, 0x40, 0x48, 0x52, 0x06, 0x98, 0x46, 0x5a, 0x2c, 0x24, 0x14, 0x3c,
	0x17, 0xac, 0x0c, 0xc7, 0x1d, 0x93, 0x66, 0x5a, 0x35, 0x3e, 0xb5, 0xde, 0xec, 0xfd, 0x6b, 0x4c,
	0xa3, 0x59, 0xad, 0x60, 0x65, 0xf8, 0xbe, 0xbb, 0xdf, 0x95, 0xe1, 0xbc, 0x55, 0x3f, 0xcd, 0xc5,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x52, 0x1f, 0x49, 0x5b, 0xe1, 0x01, 0x00, 0x00,
}
