// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ListerClient is the client API for Lister service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListerClient interface {
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
}

type listerClient struct {
	cc grpc.ClientConnInterface
}

func NewListerClient(cc grpc.ClientConnInterface) ListerClient {
	return &listerClient{cc}
}

func (c *listerClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/v1.Lister/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListerServer is the server API for Lister service.
// All implementations must embed UnimplementedListerServer
// for forward compatibility
type ListerServer interface {
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	mustEmbedUnimplementedListerServer()
}

// UnimplementedListerServer must be embedded to have forward compatible implementations.
type UnimplementedListerServer struct {
}

func (UnimplementedListerServer) ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedListerServer) mustEmbedUnimplementedListerServer() {}

// UnsafeListerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListerServer will
// result in compilation errors.
type UnsafeListerServer interface {
	mustEmbedUnimplementedListerServer()
}

func RegisterListerServer(s grpc.ServiceRegistrar, srv ListerServer) {
	s.RegisterService(&Lister_ServiceDesc, srv)
}

func _Lister_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListerServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Lister/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListerServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lister_ServiceDesc is the grpc.ServiceDesc for Lister service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lister_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Lister",
	HandlerType: (*ListerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAccounts",
			Handler:    _Lister_ListAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lister.proto",
}
