// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lister.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListAccountsRequest struct {
	Paths                []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac900d9318e049d, []int{0}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type ListAccountsResponse struct {
	State                ResponseState `protobuf:"varint,1,opt,name=state,proto3,enum=v1.ResponseState" json:"state,omitempty"`
	Accounts             []*Account    `protobuf:"bytes,2,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac900d9318e049d, []int{1}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetState() ResponseState {
	if m != nil {
		return m.State
	}
	return ResponseState_UNKNOWN
}

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Account struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac900d9318e049d, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*ListAccountsRequest)(nil), "v1.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "v1.ListAccountsResponse")
	proto.RegisterType((*Account)(nil), "v1.Account")
}

func init() {
	proto.RegisterFile("lister.proto", fileDescriptor_8ac900d9318e049d)
}

var fileDescriptor_8ac900d9318e049d = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4e, 0x83, 0x40,
	0x10, 0x0e, 0xd4, 0x56, 0xbb, 0xad, 0x26, 0x6e, 0x9b, 0x14, 0x1b, 0x7f, 0x08, 0x97, 0x12, 0x4d,
	0x97, 0x80, 0x57, 0x2f, 0x36, 0xf1, 0x64, 0x0f, 0x0d, 0xbd, 0x19, 0x13, 0xb3, 0xe0, 0x06, 0x36,
	0x52, 0x16, 0xd9, 0x01, 0xd3, 0x78, 0xf3, 0x15, 0x7c, 0x0b, 0x1f, 0xc5, 0xab, 0xaf, 0xe0, 0x83,
	0x18, 0xd8, 0xb6, 0xa9, 0xd1, 0x13, 0x33, 0xdf, 0xcf, 0x30, 0xfb, 0x0d, 0xea, 0x26, 0x5c, 0x02,
	0xcb, 0x49, 0x96, 0x0b, 0x10, 0x58, 0x2f, 0xdd, 0xe1, 0x71, 0x24, 0x44, 0x94, 0x30, 0x87, 0x66,
	0xdc, 0xa1, 0x69, 0x2a, 0x80, 0x02, 0x17, 0xa9, 0x54, 0x8a, 0x61, 0x2f, 0x67, 0x32, 0x13, 0xa9,
	0x64, 0x12, 0x28, 0x30, 0x05, 0x5a, 0x17, 0xa8, 0x37, 0xe5, 0x12, 0xae, 0xc3, 0x50, 0x14, 0x29,
	0x48, 0x9f, 0x3d, 0x17, 0x4c, 0x02, 0xee, 0xa3, 0x66, 0x46, 0x21, 0x96, 0x86, 0x66, 0x36, 0xec,
	0xb6, 0xaf, 0x1a, 0x2b, 0x46, 0xfd, 0xdf, 0x62, 0x35, 0x0f, 0x8f, 0x50, 0xb3, 0x9e, 0x69, 0x68,
	0xa6, 0x66, 0x1f, 0x78, 0x87, 0xa4, 0x74, 0xc9, 0x9a, 0x9c, 0x57, 0x84, 0xaf, 0x78, 0x3c, 0x42,
	0x7b, 0x6b, 0xb3, 0xa1, 0x9b, 0x0d, 0xbb, 0xe3, 0x75, 0x2a, 0xed, 0x0a, 0xf3, 0x37, 0xa4, 0x75,
	0x85, 0x76, 0x57, 0x35, 0xc6, 0x68, 0x27, 0xa5, 0x0b, 0x35, 0xbb, 0xed, 0xd7, 0x35, 0x3e, 0x41,
	0x28, 0x2b, 0x82, 0x84, 0x87, 0x0f, 0x4f, 0x6c, 0x69, 0xe8, 0xa6, 0x66, 0x77, 0xfd, 0xb6, 0x42,
	0x6e, 0xd9, 0xd2, 0x4b, 0x50, 0x6b, 0x5a, 0x67, 0x83, 0x03, 0xd4, 0xdd, 0xde, 0x18, 0x0f, 0xaa,
	0xdf, 0xfd, 0xf3, 0xe0, 0xa1, 0xf1, 0x97, 0x50, 0xfb, 0x5b, 0x67, 0x6f, 0x5f, 0xdf, 0xef, 0xfa,
	0x11, 0x1e, 0x38, 0xa5, 0xeb, 0xa8, 0xc8, 0xeb, 0x0f, 0x5d, 0x09, 0x27, 0xaf, 0xe8, 0x34, 0x14,
	0x0b, 0xf2, 0xc2, 0x68, 0xf2, 0x08, 0x2c, 0x8c, 0x09, 0x83, 0xd8, 0x93, 0x3c, 0x4a, 0x59, 0x4e,
	0x33, 0x4e, 0x4a, 0x77, 0xd2, 0x51, 0xdb, 0xcc, 0xaa, 0xc4, 0x67, 0xda, 0xdd, 0x79, 0xc4, 0x21,
	0x2e, 0x02, 0x12, 0x8a, 0x85, 0xb3, 0x71, 0x39, 0x95, 0x6b, 0xac, 0x6c, 0xe3, 0xea, 0x80, 0x59,
	0xe0, 0x94, 0xee, 0x87, 0xbe, 0x7f, 0x03, 0xb1, 0x37, 0xaf, 0x61, 0x52, 0xba, 0x9f, 0xdb, 0xfd,
	0x7d, 0xe9, 0x06, 0xad, 0xfa, 0x8c, 0x97, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x5e, 0x14,
	0x8b, 0x0d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ListerClient is the client API for Lister service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListerClient interface {
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
}

type listerClient struct {
	cc grpc.ClientConnInterface
}

func NewListerClient(cc grpc.ClientConnInterface) ListerClient {
	return &listerClient{cc}
}

func (c *listerClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/v1.Lister/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListerServer is the server API for Lister service.
type ListerServer interface {
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
}

// UnimplementedListerServer can be embedded to have forward compatible implementations.
type UnimplementedListerServer struct {
}

func (*UnimplementedListerServer) ListAccounts(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}

func RegisterListerServer(s *grpc.Server, srv ListerServer) {
	s.RegisterService(&_Lister_serviceDesc, srv)
}

func _Lister_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListerServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Lister/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListerServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lister_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Lister",
	HandlerType: (*ListerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAccounts",
			Handler:    _Lister_ListAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lister.proto",
}
