// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.4
// source: responsestate.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ResponseState int32

const (
	// UNKNOWN occurs when no information about the response is available.
	ResponseState_UNKNOWN ResponseState = 0
	// SUCCEEDED occurs when a request was successful.
	ResponseState_SUCCEEDED ResponseState = 1
	// DENIED occurs when a request was denied.
	ResponseState_DENIED ResponseState = 2
	// FAILED occurs when a request failed to complete.
	ResponseState_FAILED ResponseState = 3
)

// Enum value maps for ResponseState.
var (
	ResponseState_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCEEDED",
		2: "DENIED",
		3: "FAILED",
	}
	ResponseState_value = map[string]int32{
		"UNKNOWN":   0,
		"SUCCEEDED": 1,
		"DENIED":    2,
		"FAILED":    3,
	}
)

func (x ResponseState) Enum() *ResponseState {
	p := new(ResponseState)
	*p = x
	return p
}

func (x ResponseState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseState) Descriptor() protoreflect.EnumDescriptor {
	return file_responsestate_proto_enumTypes[0].Descriptor()
}

func (ResponseState) Type() protoreflect.EnumType {
	return &file_responsestate_proto_enumTypes[0]
}

func (x ResponseState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseState.Descriptor instead.
func (ResponseState) EnumDescriptor() ([]byte, []int) {
	return file_responsestate_proto_rawDescGZIP(), []int{0}
}

var File_responsestate_proto protoreflect.FileDescriptor

var file_responsestate_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x2a, 0x43, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x45, 0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x82,
	0x01, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x65, 0x61, 0x6c, 0x64, 0x74, 0x65, 0x63, 0x68,
	0x2e, 0x65, 0x74, 0x68, 0x32, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x42, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x61, 0x6c, 0x64, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x65, 0x74,
	0x68, 0x32, 0x2d, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62,
	0x2f, 0x76, 0x31, 0xaa, 0x02, 0x0d, 0x45, 0x74, 0x68, 0x32, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0xca, 0x02, 0x0d, 0x45, 0x74, 0x68, 0x32, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x5c, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_responsestate_proto_rawDescOnce sync.Once
	file_responsestate_proto_rawDescData = file_responsestate_proto_rawDesc
)

func file_responsestate_proto_rawDescGZIP() []byte {
	file_responsestate_proto_rawDescOnce.Do(func() {
		file_responsestate_proto_rawDescData = protoimpl.X.CompressGZIP(file_responsestate_proto_rawDescData)
	})
	return file_responsestate_proto_rawDescData
}

var file_responsestate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_responsestate_proto_goTypes = []interface{}{
	(ResponseState)(0), // 0: v1.ResponseState
}
var file_responsestate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_responsestate_proto_init() }
func file_responsestate_proto_init() {
	if File_responsestate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_responsestate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_responsestate_proto_goTypes,
		DependencyIndexes: file_responsestate_proto_depIdxs,
		EnumInfos:         file_responsestate_proto_enumTypes,
	}.Build()
	File_responsestate_proto = out.File
	file_responsestate_proto_rawDesc = nil
	file_responsestate_proto_goTypes = nil
	file_responsestate_proto_depIdxs = nil
}
