// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: signer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Signer_Sign_FullMethodName                   = "/v1.Signer/Sign"
	Signer_Multisign_FullMethodName              = "/v1.Signer/Multisign"
	Signer_SignBeaconAttestation_FullMethodName  = "/v1.Signer/SignBeaconAttestation"
	Signer_SignBeaconAttestations_FullMethodName = "/v1.Signer/SignBeaconAttestations"
	Signer_SignBeaconProposal_FullMethodName     = "/v1.Signer/SignBeaconProposal"
)

// SignerClient is the client API for Signer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignerClient interface {
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	Multisign(ctx context.Context, in *MultisignRequest, opts ...grpc.CallOption) (*MultisignResponse, error)
	SignBeaconAttestation(ctx context.Context, in *SignBeaconAttestationRequest, opts ...grpc.CallOption) (*SignResponse, error)
	SignBeaconAttestations(ctx context.Context, in *SignBeaconAttestationsRequest, opts ...grpc.CallOption) (*MultisignResponse, error)
	SignBeaconProposal(ctx context.Context, in *SignBeaconProposalRequest, opts ...grpc.CallOption) (*SignResponse, error)
}

type signerClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerClient(cc grpc.ClientConnInterface) SignerClient {
	return &signerClient{cc}
}

func (c *signerClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, Signer_Sign_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) Multisign(ctx context.Context, in *MultisignRequest, opts ...grpc.CallOption) (*MultisignResponse, error) {
	out := new(MultisignResponse)
	err := c.cc.Invoke(ctx, Signer_Multisign_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) SignBeaconAttestation(ctx context.Context, in *SignBeaconAttestationRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, Signer_SignBeaconAttestation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) SignBeaconAttestations(ctx context.Context, in *SignBeaconAttestationsRequest, opts ...grpc.CallOption) (*MultisignResponse, error) {
	out := new(MultisignResponse)
	err := c.cc.Invoke(ctx, Signer_SignBeaconAttestations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) SignBeaconProposal(ctx context.Context, in *SignBeaconProposalRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, Signer_SignBeaconProposal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerServer is the server API for Signer service.
// All implementations must embed UnimplementedSignerServer
// for forward compatibility
type SignerServer interface {
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	Multisign(context.Context, *MultisignRequest) (*MultisignResponse, error)
	SignBeaconAttestation(context.Context, *SignBeaconAttestationRequest) (*SignResponse, error)
	SignBeaconAttestations(context.Context, *SignBeaconAttestationsRequest) (*MultisignResponse, error)
	SignBeaconProposal(context.Context, *SignBeaconProposalRequest) (*SignResponse, error)
	mustEmbedUnimplementedSignerServer()
}

// UnimplementedSignerServer must be embedded to have forward compatible implementations.
type UnimplementedSignerServer struct {
}

func (UnimplementedSignerServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedSignerServer) Multisign(context.Context, *MultisignRequest) (*MultisignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multisign not implemented")
}
func (UnimplementedSignerServer) SignBeaconAttestation(context.Context, *SignBeaconAttestationRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBeaconAttestation not implemented")
}
func (UnimplementedSignerServer) SignBeaconAttestations(context.Context, *SignBeaconAttestationsRequest) (*MultisignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBeaconAttestations not implemented")
}
func (UnimplementedSignerServer) SignBeaconProposal(context.Context, *SignBeaconProposalRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBeaconProposal not implemented")
}
func (UnimplementedSignerServer) mustEmbedUnimplementedSignerServer() {}

// UnsafeSignerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignerServer will
// result in compilation errors.
type UnsafeSignerServer interface {
	mustEmbedUnimplementedSignerServer()
}

func RegisterSignerServer(s grpc.ServiceRegistrar, srv SignerServer) {
	s.RegisterService(&Signer_ServiceDesc, srv)
}

func _Signer_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signer_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signer_Multisign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultisignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).Multisign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signer_Multisign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).Multisign(ctx, req.(*MultisignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signer_SignBeaconAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignBeaconAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).SignBeaconAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signer_SignBeaconAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).SignBeaconAttestation(ctx, req.(*SignBeaconAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signer_SignBeaconAttestations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignBeaconAttestationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).SignBeaconAttestations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signer_SignBeaconAttestations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).SignBeaconAttestations(ctx, req.(*SignBeaconAttestationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signer_SignBeaconProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignBeaconProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).SignBeaconProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signer_SignBeaconProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).SignBeaconProposal(ctx, req.(*SignBeaconProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Signer_ServiceDesc is the grpc.ServiceDesc for Signer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Signer",
	HandlerType: (*SignerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _Signer_Sign_Handler,
		},
		{
			MethodName: "Multisign",
			Handler:    _Signer_Multisign_Handler,
		},
		{
			MethodName: "SignBeaconAttestation",
			Handler:    _Signer_SignBeaconAttestation_Handler,
		},
		{
			MethodName: "SignBeaconAttestations",
			Handler:    _Signer_SignBeaconAttestations_Handler,
		},
		{
			MethodName: "SignBeaconProposal",
			Handler:    _Signer_SignBeaconProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signer.proto",
}
