// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signer.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignRequest struct {
	// Types that are valid to be assigned to Id:
	//	*SignRequest_PublicKey
	//	*SignRequest_Account
	Id                   isSignRequest_Id `protobuf_oneof:"id"`
	Data                 []byte           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Domain               []byte           `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SignRequest) Reset()         { *m = SignRequest{} }
func (m *SignRequest) String() string { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()    {}
func (*SignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df2490657d73dbfd, []int{0}
}

func (m *SignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRequest.Unmarshal(m, b)
}
func (m *SignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRequest.Marshal(b, m, deterministic)
}
func (m *SignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRequest.Merge(m, src)
}
func (m *SignRequest) XXX_Size() int {
	return xxx_messageInfo_SignRequest.Size(m)
}
func (m *SignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignRequest proto.InternalMessageInfo

type isSignRequest_Id interface {
	isSignRequest_Id()
}

type SignRequest_PublicKey struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type SignRequest_Account struct {
	Account string `protobuf:"bytes,2,opt,name=account,proto3,oneof"`
}

func (*SignRequest_PublicKey) isSignRequest_Id() {}

func (*SignRequest_Account) isSignRequest_Id() {}

func (m *SignRequest) GetId() isSignRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SignRequest) GetPublicKey() []byte {
	if x, ok := m.GetId().(*SignRequest_PublicKey); ok {
		return x.PublicKey
	}
	return nil
}

func (m *SignRequest) GetAccount() string {
	if x, ok := m.GetId().(*SignRequest_Account); ok {
		return x.Account
	}
	return ""
}

func (m *SignRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignRequest) GetDomain() []byte {
	if m != nil {
		return m.Domain
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SignRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SignRequest_PublicKey)(nil),
		(*SignRequest_Account)(nil),
	}
}

type SignBeaconAttestationRequest struct {
	// Types that are valid to be assigned to Id:
	//	*SignBeaconAttestationRequest_PublicKey
	//	*SignBeaconAttestationRequest_Account
	Id                   isSignBeaconAttestationRequest_Id `protobuf_oneof:"id"`
	Domain               []byte                            `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Data                 *AttestationData                  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SignBeaconAttestationRequest) Reset()         { *m = SignBeaconAttestationRequest{} }
func (m *SignBeaconAttestationRequest) String() string { return proto.CompactTextString(m) }
func (*SignBeaconAttestationRequest) ProtoMessage()    {}
func (*SignBeaconAttestationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df2490657d73dbfd, []int{1}
}

func (m *SignBeaconAttestationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignBeaconAttestationRequest.Unmarshal(m, b)
}
func (m *SignBeaconAttestationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignBeaconAttestationRequest.Marshal(b, m, deterministic)
}
func (m *SignBeaconAttestationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignBeaconAttestationRequest.Merge(m, src)
}
func (m *SignBeaconAttestationRequest) XXX_Size() int {
	return xxx_messageInfo_SignBeaconAttestationRequest.Size(m)
}
func (m *SignBeaconAttestationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignBeaconAttestationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignBeaconAttestationRequest proto.InternalMessageInfo

type isSignBeaconAttestationRequest_Id interface {
	isSignBeaconAttestationRequest_Id()
}

type SignBeaconAttestationRequest_PublicKey struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type SignBeaconAttestationRequest_Account struct {
	Account string `protobuf:"bytes,2,opt,name=account,proto3,oneof"`
}

func (*SignBeaconAttestationRequest_PublicKey) isSignBeaconAttestationRequest_Id() {}

func (*SignBeaconAttestationRequest_Account) isSignBeaconAttestationRequest_Id() {}

func (m *SignBeaconAttestationRequest) GetId() isSignBeaconAttestationRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SignBeaconAttestationRequest) GetPublicKey() []byte {
	if x, ok := m.GetId().(*SignBeaconAttestationRequest_PublicKey); ok {
		return x.PublicKey
	}
	return nil
}

func (m *SignBeaconAttestationRequest) GetAccount() string {
	if x, ok := m.GetId().(*SignBeaconAttestationRequest_Account); ok {
		return x.Account
	}
	return ""
}

func (m *SignBeaconAttestationRequest) GetDomain() []byte {
	if m != nil {
		return m.Domain
	}
	return nil
}

func (m *SignBeaconAttestationRequest) GetData() *AttestationData {
	if m != nil {
		return m.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SignBeaconAttestationRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SignBeaconAttestationRequest_PublicKey)(nil),
		(*SignBeaconAttestationRequest_Account)(nil),
	}
}

type SignBeaconProposalRequest struct {
	// Types that are valid to be assigned to Id:
	//	*SignBeaconProposalRequest_PublicKey
	//	*SignBeaconProposalRequest_Account
	Id                   isSignBeaconProposalRequest_Id `protobuf_oneof:"id"`
	Domain               []byte                         `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Data                 *BeaconBlockHeader             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SignBeaconProposalRequest) Reset()         { *m = SignBeaconProposalRequest{} }
func (m *SignBeaconProposalRequest) String() string { return proto.CompactTextString(m) }
func (*SignBeaconProposalRequest) ProtoMessage()    {}
func (*SignBeaconProposalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df2490657d73dbfd, []int{2}
}

func (m *SignBeaconProposalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignBeaconProposalRequest.Unmarshal(m, b)
}
func (m *SignBeaconProposalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignBeaconProposalRequest.Marshal(b, m, deterministic)
}
func (m *SignBeaconProposalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignBeaconProposalRequest.Merge(m, src)
}
func (m *SignBeaconProposalRequest) XXX_Size() int {
	return xxx_messageInfo_SignBeaconProposalRequest.Size(m)
}
func (m *SignBeaconProposalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignBeaconProposalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignBeaconProposalRequest proto.InternalMessageInfo

type isSignBeaconProposalRequest_Id interface {
	isSignBeaconProposalRequest_Id()
}

type SignBeaconProposalRequest_PublicKey struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type SignBeaconProposalRequest_Account struct {
	Account string `protobuf:"bytes,2,opt,name=account,proto3,oneof"`
}

func (*SignBeaconProposalRequest_PublicKey) isSignBeaconProposalRequest_Id() {}

func (*SignBeaconProposalRequest_Account) isSignBeaconProposalRequest_Id() {}

func (m *SignBeaconProposalRequest) GetId() isSignBeaconProposalRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SignBeaconProposalRequest) GetPublicKey() []byte {
	if x, ok := m.GetId().(*SignBeaconProposalRequest_PublicKey); ok {
		return x.PublicKey
	}
	return nil
}

func (m *SignBeaconProposalRequest) GetAccount() string {
	if x, ok := m.GetId().(*SignBeaconProposalRequest_Account); ok {
		return x.Account
	}
	return ""
}

func (m *SignBeaconProposalRequest) GetDomain() []byte {
	if m != nil {
		return m.Domain
	}
	return nil
}

func (m *SignBeaconProposalRequest) GetData() *BeaconBlockHeader {
	if m != nil {
		return m.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SignBeaconProposalRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SignBeaconProposalRequest_PublicKey)(nil),
		(*SignBeaconProposalRequest_Account)(nil),
	}
}

type SignResponse struct {
	State                ResponseState `protobuf:"varint,1,opt,name=state,proto3,enum=v1.ResponseState" json:"state,omitempty"`
	Signature            []byte        `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SignResponse) Reset()         { *m = SignResponse{} }
func (m *SignResponse) String() string { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()    {}
func (*SignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df2490657d73dbfd, []int{3}
}

func (m *SignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResponse.Unmarshal(m, b)
}
func (m *SignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResponse.Marshal(b, m, deterministic)
}
func (m *SignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResponse.Merge(m, src)
}
func (m *SignResponse) XXX_Size() int {
	return xxx_messageInfo_SignResponse.Size(m)
}
func (m *SignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignResponse proto.InternalMessageInfo

func (m *SignResponse) GetState() ResponseState {
	if m != nil {
		return m.State
	}
	return ResponseState_UNKNOWN
}

func (m *SignResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*SignRequest)(nil), "v1.SignRequest")
	proto.RegisterType((*SignBeaconAttestationRequest)(nil), "v1.SignBeaconAttestationRequest")
	proto.RegisterType((*SignBeaconProposalRequest)(nil), "v1.SignBeaconProposalRequest")
	proto.RegisterType((*SignResponse)(nil), "v1.SignResponse")
}

func init() {
	proto.RegisterFile("signer.proto", fileDescriptor_df2490657d73dbfd)
}

var fileDescriptor_df2490657d73dbfd = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x6b, 0x37, 0x14, 0x65, 0x12, 0x28, 0x9d, 0xaa, 0x10, 0xa2, 0x94, 0x46, 0x91, 0x50,
	0x03, 0x52, 0x6d, 0xd9, 0x3c, 0x01, 0x16, 0x48, 0x91, 0xb8, 0x44, 0x8e, 0xb8, 0x20, 0x24, 0xb4,
	0xb6, 0x57, 0xce, 0xaa, 0xce, 0xae, 0xb1, 0xd7, 0x46, 0x15, 0x9c, 0x78, 0x05, 0x9e, 0x00, 0x8e,
	0xdc, 0x78, 0x0d, 0xae, 0xbc, 0x02, 0x0f, 0x82, 0x76, 0xd7, 0x21, 0x4e, 0x09, 0x37, 0x38, 0x79,
	0x77, 0x66, 0x67, 0xfe, 0x4f, 0xfe, 0x67, 0xa0, 0x5f, 0xb2, 0x94, 0xd3, 0xc2, 0xc9, 0x0b, 0x21,
	0x05, 0xda, 0xb5, 0x37, 0x1c, 0xa5, 0x42, 0xa4, 0x19, 0x75, 0x49, 0xce, 0x5c, 0xc2, 0xb9, 0x90,
	0x44, 0x32, 0xc1, 0x4b, 0xf3, 0x62, 0x08, 0x54, 0x2e, 0xfd, 0xe6, 0x7c, 0x5c, 0xd0, 0x32, 0x17,
	0xbc, 0xa4, 0xa5, 0x24, 0x92, 0x9a, 0xe0, 0xe4, 0x03, 0xf4, 0x16, 0x2c, 0xe5, 0x21, 0x7d, 0x5b,
	0xd1, 0x52, 0xe2, 0x19, 0x40, 0x5e, 0x45, 0x19, 0x8b, 0xdf, 0x5c, 0xd2, 0xab, 0x81, 0x35, 0xb6,
	0xa6, 0xfd, 0xd9, 0x5e, 0xd8, 0x35, 0xb1, 0x17, 0xf4, 0x0a, 0x87, 0x70, 0x93, 0xc4, 0xb1, 0xa8,
	0xb8, 0x1c, 0xd8, 0x63, 0x6b, 0xda, 0x9d, 0xed, 0x85, 0xeb, 0x00, 0x22, 0x74, 0x12, 0x22, 0xc9,
	0x60, 0x5f, 0x95, 0x85, 0xfa, 0x8c, 0x77, 0xe1, 0x20, 0x11, 0x2b, 0xc2, 0xf8, 0xa0, 0xa3, 0xa3,
	0xcd, 0x2d, 0xe8, 0x80, 0xcd, 0x92, 0xc9, 0x17, 0x0b, 0x46, 0x4a, 0x3e, 0xa0, 0x24, 0x16, 0xfc,
	0xa9, 0x94, 0x9a, 0x8d, 0x89, 0x7f, 0xc3, 0xb3, 0xd1, 0xde, 0x6f, 0x6b, 0xe3, 0x79, 0xc3, 0xa9,
	0x88, 0x7a, 0xfe, 0xb1, 0x53, 0x7b, 0x4e, 0x4b, 0xfa, 0x19, 0x91, 0xc4, 0xc0, 0x37, 0x90, 0x9f,
	0x2d, 0xb8, 0xbf, 0x81, 0x9c, 0x17, 0x22, 0x17, 0x25, 0xc9, 0xfe, 0x2b, 0xe1, 0xa3, 0x2d, 0xc2,
	0x13, 0x45, 0x68, 0xd4, 0x83, 0x4c, 0xc4, 0x97, 0x33, 0x4a, 0x12, 0x5a, 0x6c, 0x31, 0xbe, 0x84,
	0xbe, 0xb1, 0xd1, 0x38, 0x8c, 0xe7, 0x70, 0x43, 0xbb, 0xac, 0x81, 0x6e, 0xfb, 0x47, 0xaa, 0xc3,
	0x3a, 0xb9, 0x50, 0x89, 0xd0, 0xe4, 0x71, 0x04, 0x5d, 0x35, 0x52, 0x44, 0x56, 0x05, 0xd5, 0x7c,
	0xfd, 0x70, 0x13, 0xf0, 0xbf, 0xd9, 0x70, 0xb0, 0xd0, 0x13, 0x87, 0x01, 0x74, 0xd4, 0x09, 0x0f,
	0x55, 0xab, 0xd6, 0xc8, 0x0c, 0xef, 0x6c, 0x02, 0xa6, 0xff, 0xe4, 0xde, 0xc7, 0x1f, 0x3f, 0x3f,
	0xd9, 0x47, 0x78, 0xe8, 0xd6, 0x9e, 0x6b, 0x06, 0x56, 0x7f, 0xb0, 0x82, 0x93, 0x9d, 0x6e, 0xe3,
	0x78, 0xdd, 0xe3, 0x6f, 0x83, 0xb0, 0x43, 0x65, 0xaa, 0x55, 0x26, 0x38, 0xbe, 0xa6, 0x12, 0xe9,
	0x16, 0xa4, 0xd5, 0x3d, 0x03, 0xfc, 0xd3, 0x3f, 0x3c, 0xdd, 0xd6, 0xbc, 0xe6, 0xeb, 0x0e, 0xc1,
	0x87, 0x5a, 0xf0, 0x0c, 0x4f, 0x77, 0x0a, 0xe6, 0x4d, 0x7d, 0xf0, 0x1e, 0x1e, 0xc4, 0x62, 0xe5,
	0xbc, 0xa3, 0x24, 0x4b, 0x24, 0x8d, 0x97, 0x8e, 0x5a, 0x41, 0xf3, 0x9c, 0xe4, 0xcc, 0xa9, 0xbd,
	0xa0, 0x67, 0x7e, 0xe9, 0x5c, 0x2d, 0xe0, 0xdc, 0x7a, 0xf5, 0x38, 0x65, 0x72, 0x59, 0x45, 0x4e,
	0x2c, 0x56, 0xee, 0xef, 0x2a, 0x57, 0x55, 0x5d, 0x98, 0xb2, 0x0b, 0xb5, 0xdb, 0x79, 0xe4, 0xd6,
	0xde, 0x57, 0xfb, 0xd6, 0x73, 0xb9, 0xf4, 0x4d, 0xbd, 0x53, 0x7b, 0xdf, 0xdb, 0xf7, 0xd7, 0xb5,
	0x17, 0x1d, 0xe8, 0xad, 0x7e, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x82, 0xcd, 0x03, 0x28,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SignerClient is the client API for Signer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignerClient interface {
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	SignBeaconAttestation(ctx context.Context, in *SignBeaconAttestationRequest, opts ...grpc.CallOption) (*SignResponse, error)
	SignBeaconProposal(ctx context.Context, in *SignBeaconProposalRequest, opts ...grpc.CallOption) (*SignResponse, error)
}

type signerClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerClient(cc grpc.ClientConnInterface) SignerClient {
	return &signerClient{cc}
}

func (c *signerClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, "/v1.Signer/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) SignBeaconAttestation(ctx context.Context, in *SignBeaconAttestationRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, "/v1.Signer/SignBeaconAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) SignBeaconProposal(ctx context.Context, in *SignBeaconProposalRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, "/v1.Signer/SignBeaconProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerServer is the server API for Signer service.
type SignerServer interface {
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	SignBeaconAttestation(context.Context, *SignBeaconAttestationRequest) (*SignResponse, error)
	SignBeaconProposal(context.Context, *SignBeaconProposalRequest) (*SignResponse, error)
}

// UnimplementedSignerServer can be embedded to have forward compatible implementations.
type UnimplementedSignerServer struct {
}

func (*UnimplementedSignerServer) Sign(ctx context.Context, req *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (*UnimplementedSignerServer) SignBeaconAttestation(ctx context.Context, req *SignBeaconAttestationRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBeaconAttestation not implemented")
}
func (*UnimplementedSignerServer) SignBeaconProposal(ctx context.Context, req *SignBeaconProposalRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignBeaconProposal not implemented")
}

func RegisterSignerServer(s *grpc.Server, srv SignerServer) {
	s.RegisterService(&_Signer_serviceDesc, srv)
}

func _Signer_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Signer/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signer_SignBeaconAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignBeaconAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).SignBeaconAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Signer/SignBeaconAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).SignBeaconAttestation(ctx, req.(*SignBeaconAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signer_SignBeaconProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignBeaconProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).SignBeaconProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Signer/SignBeaconProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).SignBeaconProposal(ctx, req.(*SignBeaconProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Signer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Signer",
	HandlerType: (*SignerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _Signer_Sign_Handler,
		},
		{
			MethodName: "SignBeaconAttestation",
			Handler:    _Signer_SignBeaconAttestation_Handler,
		},
		{
			MethodName: "SignBeaconProposal",
			Handler:    _Signer_SignBeaconProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signer.proto",
}
