// Code generated by protoc-gen-go. DO NOT EDIT.
// source: walletmanager.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnlockWalletRequest struct {
	Wallet               string   `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Passphrase           []byte   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockWalletRequest) Reset()         { *m = UnlockWalletRequest{} }
func (m *UnlockWalletRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockWalletRequest) ProtoMessage()    {}
func (*UnlockWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_732534cdb62da000, []int{0}
}

func (m *UnlockWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockWalletRequest.Unmarshal(m, b)
}
func (m *UnlockWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockWalletRequest.Marshal(b, m, deterministic)
}
func (m *UnlockWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockWalletRequest.Merge(m, src)
}
func (m *UnlockWalletRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockWalletRequest.Size(m)
}
func (m *UnlockWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockWalletRequest proto.InternalMessageInfo

func (m *UnlockWalletRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *UnlockWalletRequest) GetPassphrase() []byte {
	if m != nil {
		return m.Passphrase
	}
	return nil
}

type LockWalletRequest struct {
	Wallet               string   `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockWalletRequest) Reset()         { *m = LockWalletRequest{} }
func (m *LockWalletRequest) String() string { return proto.CompactTextString(m) }
func (*LockWalletRequest) ProtoMessage()    {}
func (*LockWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_732534cdb62da000, []int{1}
}

func (m *LockWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockWalletRequest.Unmarshal(m, b)
}
func (m *LockWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockWalletRequest.Marshal(b, m, deterministic)
}
func (m *LockWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockWalletRequest.Merge(m, src)
}
func (m *LockWalletRequest) XXX_Size() int {
	return xxx_messageInfo_LockWalletRequest.Size(m)
}
func (m *LockWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockWalletRequest proto.InternalMessageInfo

func (m *LockWalletRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

type UnlockWalletResponse struct {
	State                ResponseState `protobuf:"varint,1,opt,name=state,proto3,enum=v1.ResponseState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnlockWalletResponse) Reset()         { *m = UnlockWalletResponse{} }
func (m *UnlockWalletResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockWalletResponse) ProtoMessage()    {}
func (*UnlockWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_732534cdb62da000, []int{2}
}

func (m *UnlockWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockWalletResponse.Unmarshal(m, b)
}
func (m *UnlockWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockWalletResponse.Marshal(b, m, deterministic)
}
func (m *UnlockWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockWalletResponse.Merge(m, src)
}
func (m *UnlockWalletResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockWalletResponse.Size(m)
}
func (m *UnlockWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockWalletResponse proto.InternalMessageInfo

func (m *UnlockWalletResponse) GetState() ResponseState {
	if m != nil {
		return m.State
	}
	return ResponseState_UNKNOWN
}

type LockWalletResponse struct {
	State                ResponseState `protobuf:"varint,1,opt,name=state,proto3,enum=v1.ResponseState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LockWalletResponse) Reset()         { *m = LockWalletResponse{} }
func (m *LockWalletResponse) String() string { return proto.CompactTextString(m) }
func (*LockWalletResponse) ProtoMessage()    {}
func (*LockWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_732534cdb62da000, []int{3}
}

func (m *LockWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockWalletResponse.Unmarshal(m, b)
}
func (m *LockWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockWalletResponse.Marshal(b, m, deterministic)
}
func (m *LockWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockWalletResponse.Merge(m, src)
}
func (m *LockWalletResponse) XXX_Size() int {
	return xxx_messageInfo_LockWalletResponse.Size(m)
}
func (m *LockWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LockWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LockWalletResponse proto.InternalMessageInfo

func (m *LockWalletResponse) GetState() ResponseState {
	if m != nil {
		return m.State
	}
	return ResponseState_UNKNOWN
}

func init() {
	proto.RegisterType((*UnlockWalletRequest)(nil), "v1.UnlockWalletRequest")
	proto.RegisterType((*LockWalletRequest)(nil), "v1.LockWalletRequest")
	proto.RegisterType((*UnlockWalletResponse)(nil), "v1.UnlockWalletResponse")
	proto.RegisterType((*LockWalletResponse)(nil), "v1.LockWalletResponse")
}

func init() {
	proto.RegisterFile("walletmanager.proto", fileDescriptor_732534cdb62da000)
}

var fileDescriptor_732534cdb62da000 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x49, 0xf8, 0xbe, 0x82, 0x17, 0x2b, 0x74, 0xaa, 0x35, 0x04, 0x29, 0x25, 0x1b, 0x45,
	0x69, 0x86, 0xd4, 0xb5, 0x08, 0x05, 0x77, 0x2d, 0x94, 0x94, 0x22, 0x88, 0x2e, 0xa6, 0x75, 0x48,
	0x82, 0x69, 0x26, 0x66, 0xa6, 0xe9, 0xbe, 0xaf, 0xe0, 0x5b, 0xf8, 0x1e, 0x6e, 0xdc, 0xfa, 0x0a,
	0x3e, 0x88, 0xf3, 0xa7, 0x4a, 0x6b, 0x5c, 0x88, 0xcb, 0x7b, 0x4e, 0xce, 0xef, 0xde, 0xdc, 0xb9,
	0xd0, 0x5c, 0x92, 0x34, 0xa5, 0x62, 0x4e, 0x32, 0x12, 0xd1, 0xc2, 0xcf, 0x0b, 0x26, 0x18, 0xb2,
	0xcb, 0xc0, 0x3d, 0x8a, 0x18, 0x8b, 0x52, 0x8a, 0x49, 0x9e, 0x60, 0x92, 0x65, 0x4c, 0x10, 0x91,
	0xb0, 0x8c, 0x9b, 0x2f, 0xdc, 0x66, 0x41, 0x79, 0x2e, 0x4b, 0xca, 0xa5, 0x4e, 0x8d, 0xe8, 0x0d,
	0xa1, 0x39, 0xc9, 0x52, 0x36, 0x7b, 0xb8, 0xd6, 0xcc, 0x90, 0x3e, 0x2e, 0xa4, 0x8f, 0x5a, 0x50,
	0x33, 0x4d, 0x1c, 0xab, 0x63, 0x9d, 0xec, 0x84, 0xeb, 0x0a, 0xb5, 0x01, 0x72, 0xc2, 0x79, 0x1e,
	0x17, 0x84, 0x53, 0xc7, 0x96, 0xde, 0x6e, 0xb8, 0xa1, 0x78, 0x67, 0xd0, 0x18, 0xfc, 0x16, 0xe6,
	0x5d, 0xc2, 0xfe, 0x76, 0x6f, 0x33, 0x1e, 0x3a, 0x86, 0xff, 0x7a, 0x44, 0xfd, 0xf9, 0x5e, 0xaf,
	0xe1, 0x97, 0x81, 0xff, 0x69, 0x8e, 0x95, 0x11, 0x1a, 0xdf, 0xbb, 0x00, 0x34, 0xf8, 0x7b, 0xbc,
	0xf7, 0x62, 0x41, 0xdd, 0x64, 0x87, 0x66, 0x95, 0xe8, 0x0e, 0x6a, 0x66, 0x22, 0x74, 0xa8, 0x52,
	0x3f, 0x6c, 0xc6, 0x75, 0xaa, 0x86, 0x41, 0x7b, 0x9d, 0xd5, 0xdb, 0xfb, 0x93, 0xed, 0x22, 0x07,
	0x97, 0x01, 0xde, 0x7a, 0x22, 0xbc, 0x30, 0xd0, 0x09, 0xfc, 0x53, 0xf3, 0xa2, 0x03, 0xc5, 0xa8,
	0xec, 0xc9, 0x6d, 0x7d, 0x97, 0xd7, 0xe0, 0xb6, 0x06, 0x3b, 0xa8, 0x55, 0x05, 0x2b, 0x6c, 0x7f,
	0x65, 0x41, 0x7b, 0xc6, 0xe6, 0xfe, 0x92, 0x92, 0xf4, 0x5e, 0xd0, 0x59, 0xec, 0x53, 0x11, 0xf7,
	0x78, 0x12, 0x65, 0xb4, 0x90, 0xa7, 0x20, 0xa9, 0x7d, 0xb4, 0xf5, 0x9f, 0x23, 0xf5, 0xf4, 0x23,
	0xeb, 0xe6, 0x34, 0x4a, 0x44, 0xbc, 0x98, 0xfa, 0x32, 0x8c, 0xbf, 0xc2, 0x58, 0x85, 0xbb, 0x26,
	0xdd, 0x55, 0x97, 0x94, 0x4f, 0x65, 0xdf, 0x67, 0xbb, 0x7e, 0x25, 0xf5, 0xb1, 0x96, 0x25, 0xf1,
	0x75, 0xb3, 0xbe, 0x2d, 0x83, 0x69, 0x4d, 0xdf, 0xd3, 0xf9, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc1, 0x3f, 0x4b, 0xeb, 0x9d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalletManagerClient is the client API for WalletManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletManagerClient interface {
	Unlock(ctx context.Context, in *UnlockWalletRequest, opts ...grpc.CallOption) (*UnlockWalletResponse, error)
	Lock(ctx context.Context, in *LockWalletRequest, opts ...grpc.CallOption) (*LockWalletResponse, error)
}

type walletManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletManagerClient(cc grpc.ClientConnInterface) WalletManagerClient {
	return &walletManagerClient{cc}
}

func (c *walletManagerClient) Unlock(ctx context.Context, in *UnlockWalletRequest, opts ...grpc.CallOption) (*UnlockWalletResponse, error) {
	out := new(UnlockWalletResponse)
	err := c.cc.Invoke(ctx, "/v1.WalletManager/Unlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletManagerClient) Lock(ctx context.Context, in *LockWalletRequest, opts ...grpc.CallOption) (*LockWalletResponse, error) {
	out := new(LockWalletResponse)
	err := c.cc.Invoke(ctx, "/v1.WalletManager/Lock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletManagerServer is the server API for WalletManager service.
type WalletManagerServer interface {
	Unlock(context.Context, *UnlockWalletRequest) (*UnlockWalletResponse, error)
	Lock(context.Context, *LockWalletRequest) (*LockWalletResponse, error)
}

// UnimplementedWalletManagerServer can be embedded to have forward compatible implementations.
type UnimplementedWalletManagerServer struct {
}

func (*UnimplementedWalletManagerServer) Unlock(ctx context.Context, req *UnlockWalletRequest) (*UnlockWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlock not implemented")
}
func (*UnimplementedWalletManagerServer) Lock(ctx context.Context, req *LockWalletRequest) (*LockWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lock not implemented")
}

func RegisterWalletManagerServer(s *grpc.Server, srv WalletManagerServer) {
	s.RegisterService(&_WalletManager_serviceDesc, srv)
}

func _WalletManager_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletManagerServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.WalletManager/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletManagerServer).Unlock(ctx, req.(*UnlockWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletManager_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletManagerServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.WalletManager/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletManagerServer).Lock(ctx, req.(*LockWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.WalletManager",
	HandlerType: (*WalletManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unlock",
			Handler:    _WalletManager_Unlock_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _WalletManager_Lock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "walletmanager.proto",
}
